export const students = [
  {
    id: 1,
    name: "Sophia Rodriguez",
    studentId: "STU-24012",
    grade: "Grade 10",
    section: "A",
    gradeSection: "Grade 10 - A",
    status: "Active",
  },
  {
    id: 2,
    name: "James Chen",
    studentId: "STU-24011",
    grade: "Grade 10",
    section: "B",
    gradeSection: "Grade 10 - B",
    status: "Active",
  },
  {
    id: 3,
    name: "Emily Davis",
    studentId: "STU-24010",
    grade: "Grade 9",
    section: "A",
    gradeSection: "Grade 9 - A",
    status: "Active",
  },
  {
    id: 4,
    name: "Michael Okonkwo",
    studentId: "STU-24009",
    grade: "Grade 8",
    section: "B",
    gradeSection: "Grade 8 - B",
    status: "Active",
  },
  {
    id: 5,
    name: "Isabella Garcia",
    studentId: "STU-24008",
    grade: "Grade 7",
    section: "A",
    gradeSection: "Grade 7 - A",
    status: "Pending",
  },
];
